services:
  - type: web
    name: panamanee2026
    runtime: static
    staticPublishPath: .
    buildCommand: echo 'static site'
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
